version: 0.0
os: linux
files:
 - source: .
   destination: /home/ubuntu/app
   overwrite: true
file_exist_behavior: OVERWRITE
hooks:
  AfterInstall:
   - location: scripts/restart_server
     timeout: 300
     runas: root